# Generated by Django 4.2.3 on 2023-07-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_car_color_car_color_rename_car_make_car_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(default=294832, verbose_name='Mileage'),
            preserve_default=False,
        ),
    ]
