# Generated by Django 4.2.3 on 2023-07-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_milage_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.CharField(default='img', max_length=250),
            preserve_default=False,
        ),
    ]
